DATA:
    ROOT: 'data/ssv2/videos'
    TRAIN_FILE: 'data/ssv2/annotation/something-something-v2-train.json'
    VAL_FILE: 'data/ssv2/annotation/something-something-v2-validation.json'
    DATASET: ssv2
    NUM_FRAMES: 16
    NUM_CLASSES: 174
    LABEL_LIST: 'labels/ssv2_labels.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 16
    ACCUMULATION_STEPS: 8