DATA:
    ROOT: 'data/k400/videos'
    TRAIN_FILE: 'data/k400/train.txt'
    VAL_FILE: 'data/k400/val.txt'
    DATASET: kinetics400
    NUM_FRAMES: 8
    NUM_CLASSES: 400
    LABEL_LIST: 'labels/kinetics_400_labels.csv'
MODEL:
    ARCH: ViT-B/32
TRAIN:
    BATCH_SIZE: 8
    ACCUMULATION_STEPS: 4