DATA:
    ROOT: 'data/sthelse/videos'
    TRAIN_FILE: 'data/sthelse/compositional/sthv2_com_videos_train.txt'
    VAL_FILE: 'data/sthelse/compositional/sthv2_com_videos_val.txt'
    DATASET: sthElse
    NUM_FRAMES: 16
    NUM_CLASSES: 174
    LABEL_LIST: 'labels/sthelse_com_labels.csv'
MODEL:
    ARCH: ViT-B/16
    RESUME: 'checkpoints/k600_16_16.pth'
TRAIN:
    BATCH_SIZE: 16
    ACCUMULATION_STEPS: 4
    EPOCHS: 10 # finetune 10 epochs
    WARMUP_EPOCHS: 2